name: gnn-tox21
channels:
  - conda-forge
  - pytorch
dependencies:
  - numpy
  - pytorch
  - torchvision
  - torchaudio
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyterlab
  - pip
  - pip:
    - torch-geometric
    - requests
    - deepchem>=2.7.1